# Preparing DataSet

In [1]:
import pandas as pd
import yfinance as yf

stock_symbol = 'ACN'
timeframe = '5m'
test_stock = yf.download(stock_symbol, interval=timeframe, period = "1mo")
test_stock.drop(columns = ['Adj Close'], inplace = True)

stock = pd.read_csv(f'D:/Design Credit 1/Data Sector Wise/Technology/{stock_symbol}/{stock_symbol}TimeSeries-Final.csv')
stock.drop(columns = ['Unnamed: 0'], inplace = True)
test_stock

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Volume
Datetime,,,,,
2024-05-15 09:30:00-04:00,305.000000,308.010010,304.119995,304.649994,135324
2024-05-15 09:35:00-04:00,304.880005,304.880005,302.970001,303.445007,88778
2024-05-15 09:40:00-04:00,303.450012,303.779999,302.609985,303.299988,116416
2024-05-15 09:45:00-04:00,303.255005,303.540009,302.489990,302.545013,55704
2024-05-15 09:50:00-04:00,302.529999,303.199890,302.399994,302.700012,67010
...,...,...,...,...,...
2024-06-14 15:35:00-04:00,286.100006,286.119995,285.950012,286.000000,24641
2024-06-14 15:40:00-04:00,285.970001,286.057495,285.769989,286.019989,36391
2024-06-14 15:45:00-04:00,286.000000,286.334991,285.739990,285.790009,49027
2024-06-14 15:50:00-04:00,285.779999,286.299988,285.684998,285.739990,77433
2024-06-14 15:55:00-04:00,285.790009,286.769989,285.679993,286.739990,211699

**Calculating Indicators**

In [2]:
import pandas_ta as ta

In [3]:
stock['EMA_50']=ta.ema(stock.Close, length=50)#sma ema
stock['EMA_20']=ta.ema(stock.Close, length=20)#sma ema
stock['RSI']=ta.rsi(stock.Close, length=14)
my_bbands = ta.bbands(stock.Close, length=20, std=2)
stock=stock.join(my_bbands)

In [4]:
temp = ta.macd(stock.Close)
stock=stock.join(temp)
stock.drop(columns = ['MACD_12_26_9','MACDs_12_26_9','BBP_20_2.0','BBB_20_2.0','BBM_20_2.0'],inplace = True)

In [5]:
temp = ta.cci(stock.High,stock.Low,stock.Close)
stock=stock.join(temp)

In [6]:
temp = ta.stoch(stock.High,stock.Low,stock.Close,k=10)
stock=stock.join(temp)
stock.drop(columns = ['STOCHd_10_3_3'],inplace = True)

In [7]:
temp = ta.supertrend(stock.High,stock.Low,stock.Close)
stock=stock.join(temp)
stock.drop(columns = ['SUPERTl_7_3.0','SUPERTs_7_3.0'],inplace = True)

In [8]:
temp = ta.donchian(stock.High,stock.Low)
stock=stock.join(temp)
stock.drop(columns = ['DCM_20_20'],inplace = True)

In [9]:
temp = ta.adx(stock.High,stock.Low,stock.Close)
stock=stock.join(temp)
stock.drop(columns = ['DMP_14','DMN_14'],inplace = True)
stock

,Open,High,Low,Close,Volume,EMA_50,EMA_20,RSI,BBL_20_2.0,BBU_20_2.0,MACDh_12_26_9,CCI_14_0.015,STOCHk_10_3_3,SUPERT_7_3.0,SUPERTd_7_3.0,DCL_20_20,DCU_20_20,ADX_14
0,346.923,349.025,346.743,349.025,83206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1,NaN,NaN,NaN
1,348.766,348.966,347.161,347.179,20610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
2,347.043,347.680,346.753,347.384,19546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
3,347.626,347.880,347.386,347.386,20116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
4,347.401,347.810,347.341,347.500,10577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8185,279.555,279.665,279.040,279.040,68739,280.198517,279.487845,39.856398,278.662518,280.127082,0.044135,-23.728528,61.111111,280.171895,-1,278.69,280.60,21.623859
8186,279.070,280.410,279.055,280.350,105704,280.204458,279.569955,58.979469,278.636547,280.167053,0.108940,188.933645,67.884828,278.070876,1,278.69,280.41,21.111462
8187,280.345,281.370,280.330,281.340,128463,280.248989,279.738531,67.412256,278.363278,280.556322,0.209047,321.405574,75.528386,278.980036,1,278.69,281.37,22.239447
8188,281.320,281.820,281.020,281.490,194946,280.297656,279.905338,68.469891,278.140925,280.957175,0.271948,242.087107,94.488218,279.474317,1,278.69,281.82,23.814123
8189,281.400,282.470,281.300,282.410,518960,280.380493,280.143877,74.035819,277.828120,281.577980,0.356753,203.208807,95.067918,279.715843,1,278.69,282.47,25.889046

**Instead of using absolute value we are going to use Slope of this indicators**

In [10]:
temp = ta.slope(stock.EMA_50)
stock=stock.join(temp)
stock.rename(columns = {'SLOPE_1' : 'EMA_50_slope'},inplace = True)

temp = ta.slope(stock.EMA_20)
stock=stock.join(temp)
stock.rename(columns = {'SLOPE_1' : 'EMA_20_slope'}, inplace = True)

temp = ta.slope(stock['BBL_20_2.0'])
stock = stock.join(temp)
stock.rename(columns = {'SLOPE_1' : 'BBL_20_2.0_slope'}, inplace = True)

temp = ta.slope(stock['BBU_20_2.0'])
stock = stock.join(temp)
stock.rename(columns = {'SLOPE_1' : 'BBU_20_2.0_slope'}, inplace = True)

temp = ta.slope(stock.DCL_20_20)
stock=stock.join(temp)
stock.rename(columns = {'SLOPE_1' : 'DCL_20_20_slope'},inplace = True)

temp = ta.slope(stock.DCU_20_20)
stock=stock.join(temp)
stock.rename(columns = {'SLOPE_1' : 'DCU_20_20_slope'},inplace = True)

stock.drop(columns = ['EMA_50','EMA_20','DCL_20_20','DCU_20_20','BBL_20_2.0','BBU_20_2.0'], inplace = True)
# print(stock)
stock

,Open,High,Low,Close,Volume,RSI,MACDh_12_26_9,CCI_14_0.015,STOCHk_10_3_3,SUPERT_7_3.0,SUPERTd_7_3.0,ADX_14,EMA_50_slope,EMA_20_slope,BBL_20_2.0_slope,BBU_20_2.0_slope,DCL_20_20_slope,DCU_20_20_slope
0,346.923,349.025,346.743,349.025,83206,NaN,NaN,NaN,NaN,0.000000,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,348.766,348.966,347.161,347.179,20610,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,347.043,347.680,346.753,347.384,19546,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,347.626,347.880,347.386,347.386,20116,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,347.401,347.810,347.341,347.500,10577,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8185,279.555,279.665,279.040,279.040,68739,39.856398,0.044135,-23.728528,61.111111,280.171895,-1,21.623859,-0.047286,-0.047142,0.050525,-0.196025,0.0,-0.105
8186,279.070,280.410,279.055,280.350,105704,58.979469,0.108940,188.933645,67.884828,278.070876,1,21.111462,0.005940,0.082110,-0.025971,0.039971,0.0,-0.190
8187,280.345,281.370,280.330,281.340,128463,67.412256,0.209047,321.405574,75.528386,278.980036,1,22.239447,0.044531,0.168576,-0.273269,0.389269,0.0,0.960
8188,281.320,281.820,281.020,281.490,194946,68.469891,0.271948,242.087107,94.488218,279.474317,1,23.814123,0.048667,0.166807,-0.222353,0.400853,0.0,0.450
8189,281.400,282.470,281.300,282.410,518960,74.035819,0.356753,203.208807,95.067918,279.715843,1,25.889046,0.082837,0.238539,-0.312805,0.620805,0.0,0.650

**Now with help of ATR calculating whether we should have bought or sold**

In [11]:
import numpy as np
import warnings
warnings.filterwarnings("ignore", category=pd.errors.SettingWithCopyWarning)  ##ChainedAssignmentError
warnings.filterwarnings("ignore", category=pd.errors.ChainedAssignmentError)

temp = ta.atr(stock.High,stock.Low,stock.Close)
stock=stock.join(temp)
np_array = np.zeros(len(stock))
stock['Action'] = np_array

for i in range(0,len(stock)):
    for j in range(i,len(stock)):
        temp = (stock['Close'].iloc[j] - stock['Close'].iloc[i])
        if temp>= 3*stock['ATRr_14'].iloc[i]:
            # stock['Action'][i] = 1
            stock.loc[i, 'Action'] = 1
            break
        if temp<=-3*stock['ATRr_14'].iloc[i]:
            # stock['Action'][i] = 0
            stock.loc[i, 'Action'] = 0
            break

stock.dropna(inplace = True)
stock

,Open,High,Low,Close,Volume,RSI,MACDh_12_26_9,CCI_14_0.015,STOCHk_10_3_3,SUPERT_7_3.0,SUPERTd_7_3.0,ADX_14,EMA_50_slope,EMA_20_slope,BBL_20_2.0_slope,BBU_20_2.0_slope,DCL_20_20_slope,DCU_20_20_slope,ATRr_14,Action
50,345.120,345.249,344.956,345.218,10974,50.869530,0.069818,75.110096,69.623322,345.411287,-1,28.948694,-0.014917,0.019936,0.047198,-0.120898,0.0,-0.179,0.345617,0.0
51,345.214,345.399,345.069,345.194,9656,50.420701,0.089523,103.403715,88.526554,345.411287,-1,26.842609,-0.015273,0.015752,0.030863,-0.087063,0.0,-0.170,0.344476,0.0
52,345.120,345.229,344.860,344.929,10627,45.633056,0.082992,64.470476,77.248464,345.411287,-1,25.431800,-0.025066,-0.010986,0.042198,-0.130898,0.0,0.000,0.346266,0.0
53,344.791,344.851,344.446,344.576,12174,40.162324,0.054552,-47.512578,52.079335,345.411287,-1,25.278109,-0.037926,-0.043559,-0.026802,-0.063298,0.0,-0.109,0.356228,1.0
54,344.582,344.701,344.521,344.581,11754,40.271550,0.036594,-50.129943,30.025833,345.411287,-1,25.136544,-0.036243,-0.038934,0.002362,-0.102962,0.0,-0.045,0.343406,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8185,279.555,279.665,279.040,279.040,68739,39.856398,0.044135,-23.728528,61.111111,280.171895,-1,21.623859,-0.047286,-0.047142,0.050525,-0.196025,0.0,-0.105,0.419329,1.0
8186,279.070,280.410,279.055,280.350,105704,58.979469,0.108940,188.933645,67.884828,278.070876,1,21.111462,0.005940,0.082110,-0.025971,0.039971,0.0,-0.190,0.487234,1.0
8187,280.345,281.370,280.330,281.340,128463,67.412256,0.209047,321.405574,75.528386,278.980036,1,22.239447,0.044531,0.168576,-0.273269,0.389269,0.0,0.960,0.526717,0.0
8188,281.320,281.820,281.020,281.490,194946,68.469891,0.271948,242.087107,94.488218,279.474317,1,23.814123,0.048667,0.166807,-0.222353,0.400853,0.0,0.450,0.546238,0.0
8189,281.400,282.470,281.300,282.410,518960,74.035819,0.356753,203.208807,95.067918,279.715843,1,25.889046,0.082837,0.238539,-0.312805,0.620805,0.0,0.650,0.590792,0.0

In [12]:
stock.drop(columns = ['Open','High','Low','Volume','Close','SUPERT_7_3.0','ATRr_14'],inplace = True)
stock

,RSI,MACDh_12_26_9,CCI_14_0.015,STOCHk_10_3_3,SUPERTd_7_3.0,ADX_14,EMA_50_slope,EMA_20_slope,BBL_20_2.0_slope,BBU_20_2.0_slope,DCL_20_20_slope,DCU_20_20_slope,Action
50,50.869530,0.069818,75.110096,69.623322,-1,28.948694,-0.014917,0.019936,0.047198,-0.120898,0.0,-0.179,0.0
51,50.420701,0.089523,103.403715,88.526554,-1,26.842609,-0.015273,0.015752,0.030863,-0.087063,0.0,-0.170,0.0
52,45.633056,0.082992,64.470476,77.248464,-1,25.431800,-0.025066,-0.010986,0.042198,-0.130898,0.0,0.000,0.0
53,40.162324,0.054552,-47.512578,52.079335,-1,25.278109,-0.037926,-0.043559,-0.026802,-0.063298,0.0,-0.109,1.0
54,40.271550,0.036594,-50.129943,30.025833,-1,25.136544,-0.036243,-0.038934,0.002362,-0.102962,0.0,-0.045,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8185,39.856398,0.044135,-23.728528,61.111111,-1,21.623859,-0.047286,-0.047142,0.050525,-0.196025,0.0,-0.105,1.0
8186,58.979469,0.108940,188.933645,67.884828,1,21.111462,0.005940,0.082110,-0.025971,0.039971,0.0,-0.190,1.0
8187,67.412256,0.209047,321.405574,75.528386,1,22.239447,0.044531,0.168576,-0.273269,0.389269,0.0,0.960,0.0
8188,68.469891,0.271948,242.087107,94.488218,1,23.814123,0.048667,0.166807,-0.222353,0.400853,0.0,0.450,0.0
8189,74.035819,0.356753,203.208807,95.067918,1,25.889046,0.082837,0.238539,-0.312805,0.620805,0.0,0.650,0.0

In [13]:
stock['Action']

50      0.0
51      0.0
52      0.0
53      1.0
54      1.0
       ...
8185    1.0
8186    1.0
8187    0.0
8188    0.0
8189    0.0
Name: Action, Length: 8140, dtype: float64

## Doing Exactly as Above For test Data

In [14]:
test_stock['EMA_50']=ta.ema(test_stock.Close, length=50)#sma ema
test_stock['EMA_20']=ta.ema(test_stock.Close, length=20)#sma ema
test_stock['RSI']=ta.rsi(test_stock.Close, length=14)
my_bbands = ta.bbands(test_stock.Close, length=20, std=2)
test_stock=test_stock.join(my_bbands)

In [15]:
temp = ta.macd(test_stock.Close)
test_stock=test_stock.join(temp)
test_stock.drop(columns = ['MACD_12_26_9','MACDs_12_26_9','BBP_20_2.0','BBB_20_2.0','BBM_20_2.0'],inplace = True)

In [16]:
temp = ta.cci(test_stock.High,test_stock.Low,test_stock.Close)
test_stock=test_stock.join(temp)

In [17]:
temp = ta.stoch(test_stock.High,test_stock.Low,test_stock.Close,k=10)
test_stock=test_stock.join(temp)
test_stock.drop(columns = ['STOCHd_10_3_3'],inplace = True)

In [18]:
temp = ta.supertrend(test_stock.High,test_stock.Low,test_stock.Close)
test_stock=test_stock.join(temp)
test_stock.drop(columns = ['SUPERTl_7_3.0','SUPERTs_7_3.0'],inplace = True)

In [19]:
temp = ta.donchian(test_stock.High,test_stock.Low)
test_stock=test_stock.join(temp)
test_stock.drop(columns = ['DCM_20_20'],inplace = True)

In [20]:
temp = ta.adx(test_stock.High,test_stock.Low,test_stock.Close)
test_stock=test_stock.join(temp)
test_stock.drop(columns = ['DMP_14','DMN_14'],inplace = True)
test_stock

,Open,High,Low,Close,Volume,EMA_50,EMA_20,RSI,BBL_20_2.0,BBU_20_2.0,MACDh_12_26_9,CCI_14_0.015,STOCHk_10_3_3,SUPERT_7_3.0,SUPERTd_7_3.0,DCL_20_20,DCU_20_20,ADX_14
Datetime,,,,,,,,,,,,,,,,,,
2024-05-15 09:30:00-04:00,305.000000,308.010010,304.119995,304.649994,135324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1,NaN,NaN,NaN
2024-05-15 09:35:00-04:00,304.880005,304.880005,302.970001,303.445007,88778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
2024-05-15 09:40:00-04:00,303.450012,303.779999,302.609985,303.299988,116416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
2024-05-15 09:45:00-04:00,303.255005,303.540009,302.489990,302.545013,55704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
2024-05-15 09:50:00-04:00,302.529999,303.199890,302.399994,302.700012,67010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-06-14 15:35:00-04:00,286.100006,286.119995,285.950012,286.000000,24641,285.714640,286.021251,50.592847,285.429063,286.397933,0.012395,-6.589811,53.425177,285.383116,1,285.480011,286.494995,15.482875
2024-06-14 15:40:00-04:00,285.970001,286.057495,285.769989,286.019989,36391,285.726615,286.021131,51.057335,285.451817,286.406178,0.002038,-58.343689,35.672106,285.383116,1,285.480011,286.494995,14.686798
2024-06-14 15:45:00-04:00,286.000000,286.334991,285.739990,285.790009,49027,285.729101,285.999119,45.730445,285.495849,286.388147,-0.019887,-52.608156,23.796302,285.383116,1,285.480011,286.494995,14.865974
2024-06-14 15:50:00-04:00,285.779999,286.299988,285.684998,285.739990,77433,285.729528,285.974440,44.639611,285.527123,286.373872,-0.036384,-86.396450,15.965536,285.383116,1,285.480011,286.494995,14.798927
2024-06-14 15:55:00-04:00,285.790009,286.769989,285.679993,286.739990,211699,285.769154,286.047350,63.424231,285.509547,286.513448,0.018479,166.519553,36.887316,285.383116,1,285.480011,286.769989,15.992312

In [21]:
temp = ta.slope(test_stock.EMA_50)
test_stock=test_stock.join(temp)
test_stock.rename(columns = {'SLOPE_1' : 'EMA_50_slope'},inplace = True)

temp = ta.slope(test_stock.EMA_20)
test_stock=test_stock.join(temp)
test_stock.rename(columns = {'SLOPE_1' : 'EMA_20_slope'}, inplace = True)

temp = ta.slope(test_stock['BBL_20_2.0'])
test_stock = test_stock.join(temp)
test_stock.rename(columns = {'SLOPE_1' : 'BBL_20_2.0_slope'}, inplace = True)

temp = ta.slope(test_stock['BBU_20_2.0'])
test_stock = test_stock.join(temp)
test_stock.rename(columns = {'SLOPE_1' : 'BBU_20_2.0_slope'}, inplace = True)

temp = ta.slope(test_stock.DCL_20_20)
test_stock=test_stock.join(temp)
test_stock.rename(columns = {'SLOPE_1' : 'DCL_20_20_slope'},inplace = True)

temp = ta.slope(test_stock.DCU_20_20)
test_stock=test_stock.join(temp)
test_stock.rename(columns = {'SLOPE_1' : 'DCU_20_20_slope'},inplace = True)

test_stock.drop(columns = ['EMA_50','EMA_20','DCL_20_20','DCU_20_20','BBL_20_2.0','BBU_20_2.0'], inplace = True)
# print(stock)
test_stock

,Open,High,Low,Close,Volume,RSI,MACDh_12_26_9,CCI_14_0.015,STOCHk_10_3_3,SUPERT_7_3.0,SUPERTd_7_3.0,ADX_14,EMA_50_slope,EMA_20_slope,BBL_20_2.0_slope,BBU_20_2.0_slope,DCL_20_20_slope,DCU_20_20_slope
Datetime,,,,,,,,,,,,,,,,,,
2024-05-15 09:30:00-04:00,305.000000,308.010010,304.119995,304.649994,135324,NaN,NaN,NaN,NaN,0.000000,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-15 09:35:00-04:00,304.880005,304.880005,302.970001,303.445007,88778,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-15 09:40:00-04:00,303.450012,303.779999,302.609985,303.299988,116416,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-15 09:45:00-04:00,303.255005,303.540009,302.489990,302.545013,55704,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-05-15 09:50:00-04:00,302.529999,303.199890,302.399994,302.700012,67010,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-06-14 15:35:00-04:00,286.100006,286.119995,285.950012,286.000000,24641,50.592847,0.012395,-6.589811,53.425177,285.383116,1,15.482875,0.011647,-0.002237,0.000884,0.003117,0.0,0.000000
2024-06-14 15:40:00-04:00,285.970001,286.057495,285.769989,286.019989,36391,51.057335,0.002038,-58.343689,35.672106,285.383116,1,14.686798,0.011974,-0.000120,0.022754,0.008246,0.0,0.000000
2024-06-14 15:45:00-04:00,286.000000,286.334991,285.739990,285.790009,49027,45.730445,-0.019887,-52.608156,23.796302,285.383116,1,14.865974,0.002486,-0.022012,0.044032,-0.018031,0.0,0.000000
2024-06-14 15:50:00-04:00,285.779999,286.299988,285.684998,285.739990,77433,44.639611,-0.036384,-86.396450,15.965536,285.383116,1,14.798927,0.000427,-0.024679,0.031274,-0.014275,0.0,0.000000
2024-06-14 15:55:00-04:00,285.790009,286.769989,285.679993,286.739990,211699,63.424231,0.018479,166.519553,36.887316,285.383116,1,15.992312,0.039626,0.072909,-0.017576,0.139576,0.0,0.274994

In [22]:
import numpy as np
import warnings
warnings.filterwarnings("ignore", category=pd.errors.SettingWithCopyWarning)  ##ChainedAssignmentError
warnings.filterwarnings("ignore", category=pd.errors.ChainedAssignmentError)
test_stock.reset_index(inplace=True)

temp = ta.atr(test_stock.High,test_stock.Low,test_stock.Close)
test_stock=test_stock.join(temp)
np_array = np.zeros(len(test_stock))
test_stock['Action'] = np_array

for i in range(0,len(test_stock)):
    for j in range(i,len(test_stock)):
        temp = (test_stock['Close'].iloc[j] - test_stock['Close'].iloc[i])
        if temp>= 2*test_stock['ATRr_14'].iloc[i]:
            # stock['Action'][i] = 1
            test_stock.loc[i, 'Action'] = 1
            break
        if temp<=-2*test_stock['ATRr_14'].iloc[i]:
            # stock['Action'][i] = 0
            test_stock.loc[i, 'Action'] = 0
            break

test_stock.dropna(inplace = True)
test_stock

,Datetime,Open,High,Low,Close,Volume,RSI,MACDh_12_26_9,CCI_14_0.015,STOCHk_10_3_3,...,SUPERTd_7_3.0,ADX_14,EMA_50_slope,EMA_20_slope,BBL_20_2.0_slope,BBU_20_2.0_slope,DCL_20_20_slope,DCU_20_20_slope,ATRr_14,Action
50,2024-05-15 13:40:00-04:00,306.329987,306.399994,306.269989,306.279999,12516,61.562599,-0.120807,-5.174451,33.528507,...,1,57.134384,0.080113,0.041872,0.437256,-0.249256,0.290009,0.000000,0.409491,1.0
51,2024-05-15 13:45:00-04:00,306.339996,306.339996,306.029999,306.079987,16612,57.580008,-0.138708,-145.436182,21.705701,...,1,55.328135,0.069128,0.018836,0.406799,-0.284799,0.389984,0.000000,0.402218,1.0
52,2024-05-15 13:50:00-04:00,306.160004,306.619995,306.019989,306.600006,23327,64.085325,-0.115614,59.922970,37.209605,...,1,54.276881,0.086810,0.066568,0.007213,0.049287,0.780029,0.000000,0.416652,1.0
53,2024-05-15 13:55:00-04:00,306.654999,306.670013,306.420013,306.529999,21360,62.691479,-0.105428,122.652965,46.899692,...,1,53.409611,0.080660,0.053560,0.009597,0.031403,0.000000,0.000000,0.404509,1.0
54,2024-05-15 14:00:00-04:00,306.480011,306.549988,306.149994,306.549988,20891,62.939336,-0.097881,34.405778,65.117104,...,1,51.359095,0.078281,0.050363,0.052920,0.009580,0.019989,0.000000,0.404181,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1711,2024-06-14 15:35:00-04:00,286.100006,286.119995,285.950012,286.000000,24641,50.592847,0.012395,-6.589811,53.425177,...,1,15.482875,0.011647,-0.002237,0.000884,0.003117,0.000000,0.000000,0.308678,1.0
1712,2024-06-14 15:40:00-04:00,285.970001,286.057495,285.769989,286.019989,36391,51.057335,0.002038,-58.343689,35.672106,...,1,14.686798,0.011974,-0.000120,0.022754,0.008246,0.000000,0.000000,0.307165,1.0
1713,2024-06-14 15:45:00-04:00,286.000000,286.334991,285.739990,285.790009,49027,45.730445,-0.019887,-52.608156,23.796302,...,1,14.865974,0.002486,-0.022012,0.044032,-0.018031,0.000000,0.000000,0.327725,1.0
1714,2024-06-14 15:50:00-04:00,285.779999,286.299988,285.684998,285.739990,77433,44.639611,-0.036384,-86.396450,15.965536,...,1,14.798927,0.000427,-0.024679,0.031274,-0.014275,0.000000,0.000000,0.348244,1.0
1715,2024-06-14 15:55:00-04:00,285.790009,286.769989,285.679993,286.739990,211699,63.424231,0.018479,166.519553,36.887316,...,1,15.992312,0.039626,0.072909,-0.017576,0.139576,0.000000,0.274994,0.401226,0.0

In [23]:
test_stock.drop(columns = ['Open','High','Low','Volume','Close','SUPERT_7_3.0','ATRr_14','Datetime'],inplace = True)
test_stock

,RSI,MACDh_12_26_9,CCI_14_0.015,STOCHk_10_3_3,SUPERTd_7_3.0,ADX_14,EMA_50_slope,EMA_20_slope,BBL_20_2.0_slope,BBU_20_2.0_slope,DCL_20_20_slope,DCU_20_20_slope,Action
50,61.562599,-0.120807,-5.174451,33.528507,1,57.134384,0.080113,0.041872,0.437256,-0.249256,0.290009,0.000000,1.0
51,57.580008,-0.138708,-145.436182,21.705701,1,55.328135,0.069128,0.018836,0.406799,-0.284799,0.389984,0.000000,1.0
52,64.085325,-0.115614,59.922970,37.209605,1,54.276881,0.086810,0.066568,0.007213,0.049287,0.780029,0.000000,1.0
53,62.691479,-0.105428,122.652965,46.899692,1,53.409611,0.080660,0.053560,0.009597,0.031403,0.000000,0.000000,1.0
54,62.939336,-0.097881,34.405778,65.117104,1,51.359095,0.078281,0.050363,0.052920,0.009580,0.019989,0.000000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1711,50.592847,0.012395,-6.589811,53.425177,1,15.482875,0.011647,-0.002237,0.000884,0.003117,0.000000,0.000000,1.0
1712,51.057335,0.002038,-58.343689,35.672106,1,14.686798,0.011974,-0.000120,0.022754,0.008246,0.000000,0.000000,1.0
1713,45.730445,-0.019887,-52.608156,23.796302,1,14.865974,0.002486,-0.022012,0.044032,-0.018031,0.000000,0.000000,1.0
1714,44.639611,-0.036384,-86.396450,15.965536,1,14.798927,0.000427,-0.024679,0.031274,-0.014275,0.000000,0.000000,1.0
1715,63.424231,0.018479,166.519553,36.887316,1,15.992312,0.039626,0.072909,-0.017576,0.139576,0.000000,0.274994,0.0

## Normalizing And breaking int X_Train,y_train,X_test,y_test

In [24]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))

# stock_copy = stock.copy()
# test_stock_copy = test_stock.copy()

y_train = np.array(stock['Action'])
y_test = np.array(test_stock['Action'])

X_train = stock.drop(columns=['Action'])
X_test = test_stock.drop(columns=['Action'])

sc.fit(X_train)

import joblib
joblib.dump(sc, f'{stock_symbol}MinMaxScaler.pkl')

X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [25]:
print(X_train)
X_train.shape

[[0.51344077 0.75676033 0.5804751  ... 0.59073926 0.72514162 0.52828732]
 [0.50815258 0.7609633  0.61078969 ... 0.59273635 0.72514162 0.52869597]
 [0.45174363 0.75957014 0.56907551 ... 0.59014907 0.72514162 0.53641482]
 ...
 [0.70835032 0.78645636 0.84436312 ... 0.62085116 0.72514162 0.58000363]
 [0.72081158 0.7998726  0.75937904 ... 0.62153487 0.72514162 0.55684708]
 [0.78639041 0.81796053 0.71772372 ... 0.63451722 0.72514162 0.56592808]]

(8140, 12)

In [26]:
print(X_test)
X_test.shape

[[0.63942854 0.71610205 0.49445595 ... 0.58316314 0.7354736  0.53641482]
 [0.5925049  0.71228397 0.34417552 ... 0.58106529 0.73903538 0.53641482]
 [0.66915179 0.71720959 0.56420318 ... 0.60078421 0.75293132 0.53641482]
 ...
 [0.45289108 0.73762726 0.44363412 ... 0.59681084 0.72514162 0.53641482]
 [0.44003867 0.7341086  0.40743238 ... 0.59703253 0.72514162 0.53641482]
 [0.66136265 0.74581022 0.67841381 ... 0.60611338 0.72514162 0.54890092]]

(1666, 12)

In [27]:
print(y_train)
y_train.shape

[0. 0. 0. ... 0. 0. 0.]

(8140,)

In [28]:
y_test.shape

(1666,)

# Traditional Machine Learning Model

In [29]:
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

perceptron = Perceptron()
perceptron.fit(X_train, y_train)

y_pred = perceptron.predict(X_test)

print("On test data : ", classification_report(y_test, y_pred))

y_pred = perceptron.predict(X_train)
print("On train data : ", classification_report(y_train, y_pred))

On test data :                precision    recall  f1-score   support

         0.0       0.57      0.99      0.72       945
         1.0       0.48      0.02      0.03       721

    accuracy                           0.57      1666
   macro avg       0.52      0.50      0.38      1666
weighted avg       0.53      0.57      0.42      1666

On train data :                precision    recall  f1-score   support

         0.0       0.49      0.99      0.66      4004
         1.0       0.59      0.02      0.04      4136

    accuracy                           0.50      8140
   macro avg       0.54      0.50      0.35      8140
weighted avg       0.54      0.50      0.34      8140

In [30]:
from sklearn.linear_model import LogisticRegression

# Create and train model
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train, y_train)

# Predict and print classification result
y_pred = logistic_regression.predict(X_test)

print("On test data : ", classification_report(y_test, y_pred))

y_pred = logistic_regression.predict(X_train)
print("On train data : ", classification_report(y_train, y_pred))

On test data :                precision    recall  f1-score   support

         0.0       0.60      0.44      0.51       945
         1.0       0.46      0.61      0.52       721

    accuracy                           0.52      1666
   macro avg       0.53      0.53      0.52      1666
weighted avg       0.54      0.52      0.52      1666

On train data :                precision    recall  f1-score   support

         0.0       0.56      0.42      0.48      4004
         1.0       0.55      0.68      0.60      4136

    accuracy                           0.55      8140
   macro avg       0.55      0.55      0.54      8140
weighted avg       0.55      0.55      0.54      8140

In [31]:
from sklearn.naive_bayes import GaussianNB

# Create and train model
naive_bayes = GaussianNB()
naive_bayes.fit(X_train, y_train)

# Predict and print classification result
y_pred = naive_bayes.predict(X_test)

print("On test data : ", classification_report(y_test, y_pred))

y_pred = naive_bayes.predict(X_train)
print("On train data : ", classification_report(y_train, y_pred))

On test data :                precision    recall  f1-score   support

         0.0       0.73      0.14      0.23       945
         1.0       0.45      0.93      0.61       721

    accuracy                           0.48      1666
   macro avg       0.59      0.54      0.42      1666
weighted avg       0.61      0.48      0.39      1666

On train data :                precision    recall  f1-score   support

         0.0       0.57      0.16      0.25      4004
         1.0       0.52      0.88      0.65      4136

    accuracy                           0.53      8140
   macro avg       0.54      0.52      0.45      8140
weighted avg       0.54      0.53      0.46      8140

In [32]:
from sklearn.neighbors import KNeighborsClassifier

# Create and train model
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

# Predict and print classification result
y_pred = knn.predict(X_test)

print("On test data : ", classification_report(y_test, y_pred))

y_pred = knn.predict(X_train)
print("On train data : ", classification_report(y_train, y_pred))

On test data :                precision    recall  f1-score   support

         0.0       0.64      0.62      0.63       945
         1.0       0.52      0.54      0.53       721

    accuracy                           0.59      1666
   macro avg       0.58      0.58      0.58      1666
weighted avg       0.59      0.59      0.59      1666

On train data :                precision    recall  f1-score   support

         0.0       0.76      0.74      0.75      4004
         1.0       0.76      0.78      0.77      4136

    accuracy                           0.76      8140
   macro avg       0.76      0.76      0.76      8140
weighted avg       0.76      0.76      0.76      8140

In [33]:
from sklearn.neural_network import MLPClassifier

# Create and train model
ann = MLPClassifier()
ann.fit(X_train, y_train)

# Predict and print classification result
y_pred = ann.predict(X_test)

print("On test data : ", classification_report(y_test, y_pred))

y_pred = ann.predict(X_train)
print("On train data : ", classification_report(y_train, y_pred))

On test data :                precision    recall  f1-score   support

         0.0       0.59      0.42      0.49       945
         1.0       0.45      0.62      0.52       721

    accuracy                           0.50      1666
   macro avg       0.52      0.52      0.50      1666
weighted avg       0.53      0.50      0.50      1666

On train data :                precision    recall  f1-score   support

         0.0       0.61      0.36      0.45      4004
         1.0       0.56      0.78      0.65      4136

    accuracy                           0.57      8140
   macro avg       0.59      0.57      0.55      8140
weighted avg       0.59      0.57      0.55      8140

In [34]:
from sklearn.svm import SVC
svc_rbf = SVC(kernel='poly')
svc_rbf.fit(X_train, y_train)

y_pred = svc_rbf.predict(X_test)

print("On test data : ", classification_report(y_test, y_pred))

y_pred = svc_rbf.predict(X_train)
print("On train data : ", classification_report(y_train, y_pred))

On test data :                precision    recall  f1-score   support

         0.0       0.64      0.55      0.59       945
         1.0       0.50      0.60      0.55       721

    accuracy                           0.57      1666
   macro avg       0.57      0.57      0.57      1666
weighted avg       0.58      0.57      0.57      1666

On train data :                precision    recall  f1-score   support

         0.0       0.62      0.45      0.52      4004
         1.0       0.58      0.73      0.64      4136

    accuracy                           0.59      8140
   macro avg       0.60      0.59      0.58      8140
weighted avg       0.60      0.59      0.58      8140

In [35]:
### MLP Classifier and Support vector machine with polynomial kernel, seem to be the best 
### Because along with positive trend they are also able to detect negative trend 
### whereas other are only able to predict one sided trend

## Saving The Best ML Model

In [36]:
import joblib
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline

pipeline = make_pipeline(MinMaxScaler(feature_range=(0,1)), SVC(kernel='poly'))
pipeline.fit(stock.drop(columns = ['Action']), stock['Action'])  ####X_train,y_train
joblib.dump(pipeline, f'{stock_symbol}MLmodel.pkl')

['ACNMLmodel.pkl']

In [37]:
# Load the pipeline from the file
# loaded_pipeline = joblib.load('model_pipeline.pkl')

# # Make predictions on new data
# new_data = [[5.1, 3.5, 1.4, 0.2]]  # Example new data
# predictions = loaded_pipeline.predict(new_data)
# print(predictions)

# Deep Learning Model

## ANN

In [38]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Dense
from keras.layers import TimeDistributed
# !pip install tensorflow-addons
# import tensorflow_addons as tfa
from keras.activations import sigmoid
from sklearn.metrics import classification_report
# tf.random.set_seed(20)
# np.random.seed(10)
import tensorflow as tf
import keras
from keras import optimizers
from keras.callbacks import History
from keras.models import Model
from keras.layers import Dense, Dropout, LSTM, Input, Activation, concatenate
import numpy as np

model = keras.Sequential([
    keras.layers.Dense(12,activation = 'relu'), #### Here 12 represent number of Columns in my X_train
    keras.layers.Dense(5000,activation = 'relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(5000,activation = 'relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(500,activation = 'relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1,activation = 'sigmoid')
])

model.compile(loss = 'binary_crossentropy',optimizer = 'adam', metrics = ['accuracy'])
model.fit(x = X_train,y = y_train, batch_size=1000, epochs=20,validation_split=0.2)

In [39]:
y_pred = model.predict(X_test)
#y_pred=np.where(y_pred > 0.43, 1,0)
# y_pred[0]
real_y_pred = []
for element in y_pred:
  if element>.5:
    real_y_pred.append(1)
  else:
    real_y_pred.append(0)

print(classification_report(y_test, np.array(real_y_pred)))

In [40]:
##Now Instead of passing data of just one day we are going to pass it data of some back days also let say 30 backcandles

In [41]:
def createNewDataWhichTakeBackCandlesInAccount(data_stock, backcandles = 30):
    X = []
    #print(data_set_scaled[0].size)
    #data_set_scaled=data_set.values
    backcandles = 30
    print(data_stock.shape[0])
    for j in range(12):#data_set_scaled[0].size):#2 columns are target not X
        X.append([])
        for i in range(backcandles, data_stock.shape[0]):#backcandles+2
            X[j].append(data_stock[i-backcandles:i, j])
    #move axis from 0 to position 2
    X=np.moveaxis(X, [0], [2])
    #Erase first elements of y because of backcandles to match X length
    #del(yi[0:backcandles])
    #X, yi = np.array(X), np.array(yi)
    # Choose -1 for last column, classification else -2...
    X, yi =np.array(X), np.array(data_stock[backcandles:,-1])
    y=np.reshape(yi,(len(yi),1))
    return X,y

In [42]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))

sc.fit(stock)
stock = sc.transform(stock)
test_stock = sc.transform(test_stock)

X_train,y_train = createNewDataWhichTakeBackCandlesInAccount(stock)
X_test,y_test = createNewDataWhichTakeBackCandlesInAccount(test_stock)

8140
1666

In [43]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Dense
from keras.layers import TimeDistributed
from keras.activations import sigmoid
from sklearn.metrics import classification_report
import tensorflow as tf
import keras
from keras import optimizers
from keras.callbacks import History
from keras.models import Model
from keras.layers import Dense, Dropout, LSTM, Input, Activation, concatenate
import numpy as np


model = keras.Sequential([
    keras.layers.Flatten(input_shape = (30,12)),
    keras.layers.Dense(5000,activation = 'relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1000,activation = 'relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(500,activation = 'relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1,activation = 'sigmoid')
])

model.compile(loss = 'binary_crossentropy',optimizer = 'adam', metrics = ['accuracy'])
model.fit(x = X_train,y = y_train, batch_size=200, epochs=100,validation_split=0.2)

In [44]:
y_pred = model.predict(X_test)
#y_pred=np.where(y_pred > 0.43, 1,0)
# y_pred
real_y_pred = []
for element in y_pred:
  if element>.5:
    real_y_pred.append(1)
  else:
    real_y_pred.append(0)

print(classification_report(y_test, np.array(real_y_pred)))

## CNN

In [45]:
model = keras.Sequential([
    keras.layers.Conv2D(filters = 12, kernel_size = (3,3), activation = 'relu', input_shape = (30,12,1)),
    keras.layers.MaxPooling2D((2,2)),

    keras.layers.Conv2D(filters = 13, kernel_size = (3,3), activation = 'relu'),
    keras.layers.MaxPooling2D((2,2)),
    
    keras.layers.Flatten(),
    keras.layers.Dense(5000,activation = 'relu'),
    # keras.layers.Dropout(0.5),
    keras.layers.Dense(1000,activation = 'relu'),
    # keras.layers.Dropout(0.5),
    keras.layers.Dense(100,activation = 'relu'),
    # keras.layers.Dropout(0.5),
    keras.layers.Dense(1,activation = 'sigmoid')
])

model.compile(loss = 'binary_crossentropy',optimizer = 'adam', metrics = ['accuracy'])
model.fit(x = X_train,y = y_train, batch_size=240, epochs=10,validation_split=0.2)

In [46]:
y_pred = model.predict(X_test)
#y_pred=np.where(y_pred > 0.43, 1,0)
# y_pred
real_y_pred = []
for element in y_pred:
  if element>.5:
    real_y_pred.append(1)
  else:
    real_y_pred.append(0)

print(classification_report(y_test, np.array(real_y_pred)))

## LSTM(RNN)

In [47]:
lstm_input = Input(shape=(30, 12), name='lstm_input')
lstm_layer = LSTM(1000, name='first_layer', dropout=0.33, recurrent_dropout=0.3)(lstm_input)
dense_layer = Dense(500, activation='relu', name='dense_layer')(lstm_layer)
dropout_layer = Dropout(0.4)(dense_layer)  # Adding dropout to the Dense layer
dense_layer = Dense(500, activation='relu', name='dense_layr')(dropout_layer)
dropout_layer = Dropout(0.4)(dense_layer)  # Adding dropout to the Dense layer
# Output layer
output = Dense(1, activation='sigmoid')(dropout_layer)

model = Model(inputs=lstm_input, outputs=output)
adam = optimizers.Adam()
model.compile(optimizer=adam, loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x=X_train, y=y_train, batch_size=240, epochs=100, validation_split=0.2)

WARNING:tensorflow:Layer first_layer will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
Epoch 1/100
28/28 [==============================] - 10s 284ms/step - loss: 0.6955 - accuracy: 0.5092 - val_loss: 0.6989 - val_accuracy: 0.5142
Epoch 2/100
28/28 [==============================] - 8s 277ms/step - loss: 0.6953 - accuracy: 0.5188 - val_loss: 0.6999 - val_accuracy: 0.5049
Epoch 3/100
28/28 [==============================] - 8s 272ms/step - loss: 0.6944 - accuracy: 0.5168 - val_loss: 0.7034 - val_accuracy: 0.4747
Epoch 4/100
28/28 [==============================] - 8s 282ms/step - loss: 0.6930 - accuracy: 0.5365 - val_loss: 0.6940 - val_accuracy: 0.4994
Epoch 5/100
28/28 [==============================] - 8s 278ms/step - loss: 0.6928 - accuracy: 0.5128 - val_loss: 0.7100 - val_accuracy: 0.5018
Epoch 6/100
28/28 [==============================] - 8s 276ms/step - loss: 0.6931 - accuracy: 0.5244 - val_loss: 0.6977 - val_accuracy: 0.4994
Epoch 7/100
28/28 [==============================] - 8s 275ms/step - loss: 0.6918 - accuracy: 0.5322 - val_loss: 0.6972 - val_accuracy: 0.4945
Epoch 8/100
28/28 [==============================] - 8s 271ms/step - loss: 0.6921 - accuracy: 0.5302 - val_loss: 0.6962 - val_accuracy: 0.5037
Epoch 9/100
28/28 [==============================] - 8s 277ms/step - loss: 0.6914 - accuracy: 0.5301 - val_loss: 0.7037 - val_accuracy: 0.4821
Epoch 10/100
28/28 [==============================] - 8s 279ms/step - loss: 0.6920 - accuracy: 0.5274 - val_loss: 0.6995 - val_accuracy: 0.4716
Epoch 11/100
28/28 [==============================] - 8s 270ms/step - loss: 0.6909 - accuracy: 0.5251 - val_loss: 0.6970 - val_accuracy: 0.4840
Epoch 12/100
28/28 [==============================] - 8s 275ms/step - loss: 0.6893 - accuracy: 0.5427 - val_loss: 0.6996 - val_accuracy: 0.4852
Epoch 13/100
28/28 [==============================] - 8s 278ms/step - loss: 0.6923 - accuracy: 0.5251 - val_loss: 0.6979 - val_accuracy: 0.4803
Epoch 14/100
28/28 [==============================] - 8s 281ms/step - loss: 0.6917 - accuracy: 0.5338 - val_loss: 0.6991 - val_accuracy: 0.4760
Epoch 15/100
28/28 [==============================] - 8s 287ms/step - loss: 0.6925 - accuracy: 0.5211 - val_loss: 0.6996 - val_accuracy: 0.4741
Epoch 16/100
28/28 [==============================] - 8s 277ms/step - loss: 0.6893 - accuracy: 0.5442 - val_loss: 0.7043 - val_accuracy: 0.5018
Epoch 17/100
28/28 [==============================] - 8s 274ms/step - loss: 0.6889 - accuracy: 0.5351 - val_loss: 0.7036 - val_accuracy: 0.4402
Epoch 18/100
28/28 [==============================] - 8s 273ms/step - loss: 0.6877 - accuracy: 0.5345 - val_loss: 1.9454 - val_accuracy: 0.4692
Epoch 19/100
28/28 [==============================] - 8s 276ms/step - loss: 0.7281 - accuracy: 0.5142 - val_loss: 0.6978 - val_accuracy: 0.4747
Epoch 20/100
28/28 [==============================] - 8s 281ms/step - loss: 0.6933 - accuracy: 0.5129 - val_loss: 0.6974 - val_accuracy: 0.4710
Epoch 21/100
28/28 [==============================] - 8s 273ms/step - loss: 0.6909 - accuracy: 0.5264 - val_loss: 0.6999 - val_accuracy: 0.5080
Epoch 22/100
28/28 [==============================] - 8s 276ms/step - loss: 0.6898 - accuracy: 0.5322 - val_loss: 0.6953 - val_accuracy: 0.4988
Epoch 23/100
28/28 [==============================] - 8s 273ms/step - loss: 0.6905 - accuracy: 0.5330 - val_loss: 0.6968 - val_accuracy: 0.5006
Epoch 24/100
28/28 [==============================] - 8s 281ms/step - loss: 0.6900 - accuracy: 0.5316 - val_loss: 0.7150 - val_accuracy: 0.4501
Epoch 25/100
28/28 [==============================] - 8s 276ms/step - loss: 0.6936 - accuracy: 0.5211 - val_loss: 0.6960 - val_accuracy: 0.5203
Epoch 26/100
28/28 [==============================] - 8s 276ms/step - loss: 0.6900 - accuracy: 0.5342 - val_loss: 0.6991 - val_accuracy: 0.5166
Epoch 27/100
28/28 [==============================] - 8s 277ms/step - loss: 0.6890 - accuracy: 0.5344 - val_loss: 0.7038 - val_accuracy: 0.5142
Epoch 28/100
28/28 [==============================] - 8s 276ms/step - loss: 0.6887 - accuracy: 0.5368 - val_loss: 0.7061 - val_accuracy: 0.5068
Epoch 29/100
28/28 [==============================] - 8s 274ms/step - loss: 0.6871 - accuracy: 0.5379 - val_loss: 0.6947 - val_accuracy: 0.4723
Epoch 30/100
28/28 [==============================] - 8s 273ms/step - loss: 0.6881 - accuracy: 0.5361 - val_loss: 0.7047 - val_accuracy: 0.5055
Epoch 31/100
28/28 [==============================] - 8s 282ms/step - loss: 0.6878 - accuracy: 0.5439 - val_loss: 0.7040 - val_accuracy: 0.4587
Epoch 32/100
28/28 [==============================] - 8s 279ms/step - loss: 0.6889 - accuracy: 0.5348 - val_loss: 0.7144 - val_accuracy: 0.4988
Epoch 33/100
28/28 [==============================] - 8s 280ms/step - loss: 0.6879 - accuracy: 0.5465 - val_loss: 0.6944 - val_accuracy: 0.5210
Epoch 34/100
28/28 [==============================] - 8s 276ms/step - loss: 0.6919 - accuracy: 0.5277 - val_loss: 0.6952 - val_accuracy: 0.4932
Epoch 35/100
28/28 [==============================] - 8s 282ms/step - loss: 0.6894 - accuracy: 0.5362 - val_loss: 0.6963 - val_accuracy: 0.4982
Epoch 36/100
28/28 [==============================] - 8s 273ms/step - loss: 0.6915 - accuracy: 0.5311 - val_loss: 0.6984 - val_accuracy: 0.4772
Epoch 37/100
28/28 [==============================] - 8s 274ms/step - loss: 0.6900 - accuracy: 0.5339 - val_loss: 0.7047 - val_accuracy: 0.4741
Epoch 38/100
28/28 [==============================] - 8s 281ms/step - loss: 0.6915 - accuracy: 0.5287 - val_loss: 0.6946 - val_accuracy: 0.5080
Epoch 39/100
28/28 [==============================] - 8s 272ms/step - loss: 0.6919 - accuracy: 0.5268 - val_loss: 0.6960 - val_accuracy: 0.4988
Epoch 40/100
28/28 [==============================] - 8s 273ms/step - loss: 0.6896 - accuracy: 0.5378 - val_loss: 0.6975 - val_accuracy: 0.4926
Epoch 41/100
28/28 [==============================] - 8s 276ms/step - loss: 0.6871 - accuracy: 0.5470 - val_loss: 0.7042 - val_accuracy: 0.4858
Epoch 42/100
28/28 [==============================] - 8s 278ms/step - loss: 0.6877 - accuracy: 0.5444 - val_loss: 0.7025 - val_accuracy: 0.4821
Epoch 43/100
28/28 [==============================] - 8s 275ms/step - loss: 0.6857 - accuracy: 0.5478 - val_loss: 0.6898 - val_accuracy: 0.5469
Epoch 44/100
28/28 [==============================] - 8s 276ms/step - loss: 0.6917 - accuracy: 0.5259 - val_loss: 0.6957 - val_accuracy: 0.4945
Epoch 45/100
28/28 [==============================] - 8s 274ms/step - loss: 0.6894 - accuracy: 0.5334 - val_loss: 0.8846 - val_accuracy: 0.4605
Epoch 46/100
28/28 [==============================] - 8s 271ms/step - loss: 0.6972 - accuracy: 0.5231 - val_loss: 0.6945 - val_accuracy: 0.4840
Epoch 47/100
28/28 [==============================] - 8s 276ms/step - loss: 0.6902 - accuracy: 0.5373 - val_loss: 0.7005 - val_accuracy: 0.5111
Epoch 48/100
28/28 [==============================] - 8s 281ms/step - loss: 0.6905 - accuracy: 0.5244 - val_loss: 0.7024 - val_accuracy: 0.5006
Epoch 49/100
28/28 [==============================] - 8s 274ms/step - loss: 0.6884 - accuracy: 0.5378 - val_loss: 0.7051 - val_accuracy: 0.4655
Epoch 50/100
28/28 [==============================] - 8s 276ms/step - loss: 0.6887 - accuracy: 0.5415 - val_loss: 0.7019 - val_accuracy: 0.5055
Epoch 51/100
28/28 [==============================] - 8s 286ms/step - loss: 0.6902 - accuracy: 0.5333 - val_loss: 0.6952 - val_accuracy: 0.5012
Epoch 52/100
28/28 [==============================] - 8s 273ms/step - loss: 0.6904 - accuracy: 0.5193 - val_loss: 0.7012 - val_accuracy: 0.4642
Epoch 53/100
28/28 [==============================] - 8s 276ms/step - loss: 0.6868 - accuracy: 0.5427 - val_loss: 0.7039 - val_accuracy: 0.4747
Epoch 54/100
28/28 [==============================] - 8s 281ms/step - loss: 0.6869 - accuracy: 0.5350 - val_loss: 0.7023 - val_accuracy: 0.4877
Epoch 55/100
28/28 [==============================] - 8s 276ms/step - loss: 0.6868 - accuracy: 0.5478 - val_loss: 0.7029 - val_accuracy: 0.4889
Epoch 56/100
28/28 [==============================] - 8s 276ms/step - loss: 0.6866 - accuracy: 0.5453 - val_loss: 0.7081 - val_accuracy: 0.4772
Epoch 57/100
28/28 [==============================] - 8s 285ms/step - loss: 0.6869 - accuracy: 0.5456 - val_loss: 0.7071 - val_accuracy: 0.4618
Epoch 58/100
28/28 [==============================] - 8s 282ms/step - loss: 0.6827 - accuracy: 0.5617 - val_loss: 0.7079 - val_accuracy: 0.4994
Epoch 59/100
28/28 [==============================] - 8s 275ms/step - loss: 0.6852 - accuracy: 0.5478 - val_loss: 0.7119 - val_accuracy: 0.4655
Epoch 60/100
28/28 [==============================] - 8s 269ms/step - loss: 0.6784 - accuracy: 0.5735 - val_loss: 0.7186 - val_accuracy: 0.5043
Epoch 61/100
28/28 [==============================] - 8s 287ms/step - loss: 0.6903 - accuracy: 0.5331 - val_loss: 0.7058 - val_accuracy: 0.4692
Epoch 62/100
28/28 [==============================] - 8s 281ms/step - loss: 0.6829 - accuracy: 0.5490 - val_loss: 0.7558 - val_accuracy: 0.4309
Epoch 63/100
28/28 [==============================] - 8s 282ms/step - loss: 0.6896 - accuracy: 0.5482 - val_loss: 0.7019 - val_accuracy: 0.4895
Epoch 64/100
28/28 [==============================] - 8s 273ms/step - loss: 0.6822 - accuracy: 0.5566 - val_loss: 0.7010 - val_accuracy: 0.5043
Epoch 65/100
28/28 [==============================] - 8s 282ms/step - loss: 0.6849 - accuracy: 0.5336 - val_loss: 0.7069 - val_accuracy: 0.4766
Epoch 66/100
28/28 [==============================] - 8s 278ms/step - loss: 0.6796 - accuracy: 0.5630 - val_loss: 0.7166 - val_accuracy: 0.5000
Epoch 67/100
28/28 [==============================] - 8s 300ms/step - loss: 0.6815 - accuracy: 0.5694 - val_loss: 0.7177 - val_accuracy: 0.4568
Epoch 68/100
28/28 [==============================] - 8s 292ms/step - loss: 0.6796 - accuracy: 0.5598 - val_loss: 0.7454 - val_accuracy: 0.4414
Epoch 69/100
28/28 [==============================] - 8s 288ms/step - loss: 0.6816 - accuracy: 0.5581 - val_loss: 0.7048 - val_accuracy: 0.5037
Epoch 70/100
28/28 [==============================] - 8s 277ms/step - loss: 0.6747 - accuracy: 0.5811 - val_loss: 0.7284 - val_accuracy: 0.4908
Epoch 71/100
28/28 [==============================] - 8s 284ms/step - loss: 0.6775 - accuracy: 0.5738 - val_loss: 0.7505 - val_accuracy: 0.4420
Epoch 72/100
28/28 [==============================] - 8s 272ms/step - loss: 0.6832 - accuracy: 0.5663 - val_loss: 0.7155 - val_accuracy: 0.4605
Epoch 73/100
28/28 [==============================] - 8s 282ms/step - loss: 0.6737 - accuracy: 0.5880 - val_loss: 0.7309 - val_accuracy: 0.4476
Epoch 74/100
28/28 [==============================] - 8s 273ms/step - loss: 0.6812 - accuracy: 0.5495 - val_loss: 0.7215 - val_accuracy: 0.4741
Epoch 75/100
28/28 [==============================] - 8s 274ms/step - loss: 0.6797 - accuracy: 0.5687 - val_loss: 0.7303 - val_accuracy: 0.4482
Epoch 76/100
28/28 [==============================] - 8s 282ms/step - loss: 0.6734 - accuracy: 0.5818 - val_loss: 0.7210 - val_accuracy: 0.5006
Epoch 77/100
28/28 [==============================] - 8s 283ms/step - loss: 0.6752 - accuracy: 0.5869 - val_loss: 0.7184 - val_accuracy: 0.4846
Epoch 78/100
28/28 [==============================] - 8s 293ms/step - loss: 0.6840 - accuracy: 0.5455 - val_loss: 0.7043 - val_accuracy: 0.4710
Epoch 79/100
28/28 [==============================] - 8s 278ms/step - loss: 0.6790 - accuracy: 0.5657 - val_loss: 0.7237 - val_accuracy: 0.4649
Epoch 80/100
28/28 [==============================] - 8s 280ms/step - loss: 0.6876 - accuracy: 0.5279 - val_loss: 0.7028 - val_accuracy: 0.4698
Epoch 81/100
28/28 [==============================] - 8s 280ms/step - loss: 0.6805 - accuracy: 0.5487 - val_loss: 0.7111 - val_accuracy: 0.4747
Epoch 82/100
28/28 [==============================] - 8s 274ms/step - loss: 0.6797 - accuracy: 0.5593 - val_loss: 0.7041 - val_accuracy: 0.4926
Epoch 83/100
28/28 [==============================] - 8s 281ms/step - loss: 0.6771 - accuracy: 0.5555 - val_loss: 0.7457 - val_accuracy: 0.4544
Epoch 84/100
28/28 [==============================] - 8s 278ms/step - loss: 0.6838 - accuracy: 0.5396 - val_loss: 0.7036 - val_accuracy: 0.4975
Epoch 85/100
28/28 [==============================] - 8s 280ms/step - loss: 0.6764 - accuracy: 0.5721 - val_loss: 0.7178 - val_accuracy: 0.4883
Epoch 86/100
28/28 [==============================] - 8s 278ms/step - loss: 0.6724 - accuracy: 0.5939 - val_loss: 0.7383 - val_accuracy: 0.4550
Epoch 87/100
28/28 [==============================] - 8s 272ms/step - loss: 0.6749 - accuracy: 0.5797 - val_loss: 0.7053 - val_accuracy: 0.5228
Epoch 88/100
28/28 [==============================] - 8s 278ms/step - loss: 0.6702 - accuracy: 0.5923 - val_loss: 0.7085 - val_accuracy: 0.5265
Epoch 89/100
28/28 [==============================] - 8s 283ms/step - loss: 0.6765 - accuracy: 0.5633 - val_loss: 0.7467 - val_accuracy: 0.4889
Epoch 90/100
28/28 [==============================] - 8s 277ms/step - loss: 0.6799 - accuracy: 0.5903 - val_loss: 0.7175 - val_accuracy: 0.4753
Epoch 91/100
28/28 [==============================] - 8s 273ms/step - loss: 0.6721 - accuracy: 0.5846 - val_loss: 0.7090 - val_accuracy: 0.5025
Epoch 92/100
28/28 [==============================] - 8s 280ms/step - loss: 0.6692 - accuracy: 0.5845 - val_loss: 0.7235 - val_accuracy: 0.4969
Epoch 93/100
28/28 [==============================] - 8s 286ms/step - loss: 0.6693 - accuracy: 0.5920 - val_loss: 0.7123 - val_accuracy: 0.5148
Epoch 94/100
28/28 [==============================] - 8s 278ms/step - loss: 0.6690 - accuracy: 0.5962 - val_loss: 0.7297 - val_accuracy: 0.4858
Epoch 95/100
28/28 [==============================] - 8s 273ms/step - loss: 0.6676 - accuracy: 0.6034 - val_loss: 0.7242 - val_accuracy: 0.5025
Epoch 96/100
28/28 [==============================] - 8s 273ms/step - loss: 0.6688 - accuracy: 0.5868 - val_loss: 0.6991 - val_accuracy: 0.5345
Epoch 97/100
28/28 [==============================] - 8s 274ms/step - loss: 0.6699 - accuracy: 0.5914 - val_loss: 0.7170 - val_accuracy: 0.5136
Epoch 98/100
28/28 [==============================] - 8s 275ms/step - loss: 0.6657 - accuracy: 0.6042 - val_loss: 0.7254 - val_accuracy: 0.4864
Epoch 99/100
28/28 [==============================] - 8s 275ms/step - loss: 0.6631 - accuracy: 0.6088 - val_loss: 0.7195 - val_accuracy: 0.5111
Epoch 100/100
28/28 [==============================] - 8s 277ms/step - loss: 0.6674 - accuracy: 0.6003 - val_loss: 0.7068 - val_accuracy: 0.5092

In [48]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test)
#y_pred=np.where(y_pred > 0.43, 1,0)
real_y_pred = []
for element in y_pred:
  if element>.5:
    real_y_pred.append(1)
  else:
    real_y_pred.append(0)

print(classification_report(y_test, np.array(real_y_pred)))

52/52 [==============================] - 1s 22ms/step
              precision    recall  f1-score   support

         0.0       0.57      0.64      0.61       944
         1.0       0.41      0.34      0.37       692

    accuracy                           0.52      1636
   macro avg       0.49      0.49      0.49      1636
weighted avg       0.50      0.52      0.51      1636

## Saving The Best DL model

In [49]:
# import joblib
# joblib.dump(sc, 'scaler.pkl')

In [50]:
model.save(f'{stock_symbol}lstm_model.h5')

In [51]:
# from sklearn.preprocessing import FunctionTransformer
# from sklearn.pipeline import Pipeline
# from tensorflow.keras.models import load_model
# scaler = joblib.load(f'{stock_symbol}MinMaxScaler.pkl')
# model = load_model(f'{stock_symbol}lstm_model.h5')

In [52]:
# def createNewDataWhichTakeBackCandlesInAccount2(data_stock, backcandles=30):
#     X = []
#     for j in range(12):
#         X.append([])
#         for i in range(backcandles, data_stock.shape[0]):
#             X[j].append(data_stock[i-backcandles:i, j])
#     X = np.moveaxis(X, [0], [2])
#     return np.array(X)

# # Define the predict function
# def predict_with_lstm(X):
#     return model.predict(X)

In [53]:
# reshape_transformer = FunctionTransformer(lambda data: createNewDataWhichTakeBackCandlesInAccount2(data, backcandles=30), validate=False)
# predict_transformer = FunctionTransformer(predict_with_lstm, validate=False)

In [54]:
# pipeline = Pipeline([
#     ('scaler', scaler),
#     ('reshape', reshape_transformer),
#     ('predict', predict_transformer)
# ])

In [55]:
# predictions = pipeline.transform(test_stock.drop(columns = ['Action']))

In [56]:
# from sklearn.metrics import classification_report
# # y_pred = model.predict(X_test)
# #y_pred=np.where(y_pred > 0.43, 1,0)
# real_y_pred = []
# for element in predictions:
#   if element>.5:
#     real_y_pred.append(1)
#   else:
#     real_y_pred.append(0)

# print(classification_report(y_test, np.array(real_y_pred)))